version: '3'

services:
  db:
    build:
      context: .
      dockerfile: /Dockerfile-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: qwer123!
      MYSQL_DATABASE: rust_microservice
      MYSQL_TCP_PORT: 3307
    ports:
      - "3307:3307"
  server:
    build:
      context: .
      dockerfile: /Dockerfile
    ports:
      - "8080:80"
    environment:
      DATABASE_URL: mysql://root:qwer123!@db:3307/rust_microservice